### ISSUE TITLE
Question: Search by index with equal comparison

### ISSUE THREAD

**Issue by snovichkov** [tidwall/buntdb#26]
Is it somehow possible to search by index with equal comparison (by value)? Do You planed to create a custom method for that?

Thanks!

**Comment by tidwall** [comment]
Hi Sergey,

In order to do an equal comparison by value, you'll need to execute an `AscendGreaterOrEqual` and then do a comparison on each item from inside the iterator. 

Example code: https://github.com/tidwall/buntdb/issues/18#issuecomment-281130798

Perhaps it's possible to add something like an `AscendEqual` method which wraps around the method above.

**Comment by snovichkov** [comment]
Thanks!
