### ISSUE TITLE
Sliding Expiration and Callback

### ISSUE THREAD

**Issue by dc0d** [tidwall/buntdb#32]
This is a feature request - if it's proper to add them.

1. Adding sliding TTL; on each get operation, if the entry has a TTL and a sliding flag is set, the absolute internal expiration time will be shifted into future.
2. Setting a callback like `func(key, value string)` that will be called (in it's own new goroutine) when an entry gets expired.

Since these are optional, they would affect performance only if they are present.

**Comment by tidwall** [comment]
Hi Kaven, 

It's an interesting idea. I'm wondering how the implementation would look. 

> 1. Adding sliding TTL; on each get operation, if the entry has a TTL and a sliding flag is set, the absolute internal expiration time will be shifted into future.

A Get operation that triggers an update to the TTL would be mutable and require a read/write transaction from inside an `Update` call, and I think it would need to write to the AOF file in order to persist to disk. I'm worried this might cause confusion from an API perspective because it's common to call Get from inside `View`, which would in turn throw an error for an otherwise safe operation.

> 2. Setting a callback like func(key, value string) that will be called (in it's own new goroutine) when an entry gets expired.

This may be the better option because it's more flexible. Perhaps the user want to update the TTL, or perhaps do a cascading operation that also modifies other records. Though I would probably have a signature like `func(key value string, tx *buntdb.Tx) error` where the transaction is the same read/write transaction that performed the purging for the key. This is important because we don't want another `Update` possibly modifying the key mid-stream. Also I think a regular callback would suffice and we could avoid additional goroutines.

**Comment by dc0d** [comment]
Ah! `func(key value string, tx *buntdb.Tx) error` is very smart! Should it be added to the constructor (`Open(...)`) or be part of `Set(...)` options?

On point `1.` I was thinking of saving times as `int64` and do `atomic.AddInt64(...)` without changing the logic of the `Tx`. But your solution is better.

**Comment by dc0d** [comment]
There is `OnExpired(keys)` as part of the db config.

There are two possible ways to add this:

1. Changing the current semantics and change the signature of `OnExpired(...)` or
2. Adding another function to config like `HandleExpired(...)` which will be called inside the update `Tx` of `backgroundManager()`.

Which one seems a better approach for `buntdb` (considering other packages are importing it and the first approach breaks API while is cleaner)?

**Comment by dc0d** [comment]
Yet again, this approach may make the manager too slow and might damage performance because the manager holds an update lock for too long.

Any thoughts?

**Comment by tidwall** [comment]
> There is OnExpired(keys) as part of the db config.

What do you know. There it is! I forgot about that one.

I don't think that that handler will work as is though, because the value isn't included with the callback. Also it's outside a transaction which isn't ideal.

> 1. Changing the current semantics and change the signature of OnExpired(...) or
> 2. Adding another function to config like HandleExpired(...) which will be called inside the update Tx of backgroundManager() - and it has that signature that you have described.

Definitely number `2.` I don't think it's a good idea to break the existing API. Perhaps for clarity the function signature could be:

```go
type Config {
	OnExpiredSync func(key, value string, opts *SetOptions, tx *Transaction) error
}
```
The suffix `Sync` indicates that the operation is in-sync with the database.
The `opts` param would include the previous TTL (and other future fields) in case that's needed.

#### *From a previous comment*

> On point 1. I was thinking of saving times as int64 and do atomic.AddInt64(...) without changing the logic of the Tx.

I think this might work actually. If the `SetOptions` contains a `Sliding` bool field, then for every `Get` operation on that field an internal time is updated. Then when the operation to expire that key fires, we would first look to see if that field is set to a positive value and move the internal time forward. 

We'd need to somehow store that the operation is sliding in the AOF file. Which would not be backwards compatible.

https://github.com/tidwall/buntdb/blob/master/buntdb.go#L1210-L1216

**Comment by dc0d** [comment]
Actually `OnExpiredSync(...)` is the simplest and most clear one to implement (IMO). But I had to study it through so no one would get suspicious about me being lazy! :)

I'll send a PR - ASAPossible.

**Comment by tidwall** [comment]
Sounds good. 👍

**Comment by dc0d** [comment]
One important and interesting thing about `OnExpired` - the current implementation.

The expired entries will not be deleted if `OnExpired` is present, only reported.

The expired entries will be deleted only if no `OnExpired` is provided.

So if `OnExpired` is provided, then the expired entries will not be deleted and it's the responsibility of `OnExpired` to delete them - or set them again which allows us to implement sliding timeouts with current `buntdb`.

Look at [buntdb.go#568](https://github.com/tidwall/buntdb/blob/master/buntdb.go#L568).

I think it should get properly described inside the document of `OnExpired`. That's all needed. :)

Sending a PR for the comment - if you are fine with current implementation, which I think it is already smart and clean but unclear (no comments!).

**Comment by dc0d** [comment]
I'm sorry. I was wrong. Apparently I should leave this for sometime and then go to implement `OnExpiredSync`.

**Comment by dc0d** [comment]
Any updates?

**Comment by tidwall** [comment]
Super sorry. This issue fell off my radar. 

I'll look at asap and let you know if I run into any problems. 

Thanks!

**Comment by tidwall** [comment]
Looks great. Thanks a ton for the contribution!
