### ISSUE TITLE
Q: why strings?

### ISSUE THREAD

**Issue by ivanjaros** [tidwall/buntdb#40]
I'm just curious as to why keys and values are strings and not byte slices like it is more common with other Go databases/kv stores like Badger or Bolt?

Looking at the code I see you are using the first character of a new line in the db file as metadata info which I think can be easily done with bytes as well.

Is this because SummitDB and GJSON, SJSON were planned beforehand or is there a different reason for this decision?

**Comment by tidwall** [comment]
Hi Ivan, 

I chose to use strings instead of byte slices because I wanted to avoid keeping mutable bytes in memory. I find strings easier to maintain and it gives me the warm fuzzies that data won't accidentally be overwritten. Strings also takes up a tiny bit less header space (16 bytes vs 24 bytes), which has the small benefit of using less memory.

I generally default to strings over byte slices for all of my projects.

**Comment by mitar** [comment]
I was also surprised by this. Now I have to convert to string from bytes everywhere. :-(
