### ISSUE TITLE
Is there a another way to avoid with deprecate warning ?

### ISSUE THREAD

**Issue by yourbest** [tidwall/buntdb#49]
Thanks in advance..
I'm new to buntdb. but while Testng example code, I got a message about deprecated method.
for example, below ....
db.CreateIndex("ages", "user:*:age", buntdb.IndexInt)

readme.md is too old ? if not, (in source code) comment is misspelled ?

**Comment by rbg** [comment]
you should be using transactions not the db object. Hence the deprecate warning.

**Comment by tidwall** [comment]
Shoot! The README is out of date. As @rbg mentions, it's recommended using a transaction. 

```go
err := db.Update(func(tx *buntdb.Tx) error {
    return tx.CreateIndex("ages", "user:*:age", buntdb.IndexInt)
})
```

**Comment by DesperateL** [comment]
thx

**Comment by tidwall** [comment]
I ended up removing the deprecation warning. 
For simplicity, it seems that most people use `db.CreateIndex`, including me.
The only way that I see a `CreateIndex` failing is when it's using an existing name, and because the operation cannot affect the datas integrity, I think it should be fine to use at the `db` level.
